// Complete exercise library - pre-built, not AI generated
// These are always available to all users regardless of profile

export const EXERCISE_LIBRARY = [
  // ─── STRETCHES ───────────────────────────────────────────────
  { name: "Hip Flexor Lunge Stretch", type: "stretch", difficulty: "easy", duration_seconds: 40, target_areas: ["Hips", "Quads"], sports: ["running","football","basketball","rugby","cycling"], description: "Step forward into a lunge, drop your back knee to the floor. Push your hips forward until you feel a stretch in the front of your back hip. Keep your torso upright. Hold for 40 seconds each side.", injury_prevention_for: ["Hip pain", "Lower back pain", "Knee pain"] },
  { name: "Standing Quad Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Quads", "Knees"], sports: ["running","football","basketball","cycling","rugby"], description: "Stand on one leg, pull your other foot up behind you toward your glutes. Keep knees together and stand tall. Hold 30 seconds each side.", injury_prevention_for: ["Knee pain", "Quad strain"] },
  { name: "Hamstring Stretch (Standing)", type: "stretch", difficulty: "easy", duration_seconds: 40, target_areas: ["Hamstrings"], sports: ["running","football","basketball","rugby","tennis"], description: "Place one foot on a slightly raised surface. Keep your leg straight and hinge forward at the hips until you feel a stretch in the back of your thigh. Hold 40 seconds each side.", injury_prevention_for: ["Hamstring strain", "Lower back pain"] },
  { name: "Seated Hamstring Stretch", type: "stretch", difficulty: "easy", duration_seconds: 40, target_areas: ["Hamstrings", "Lower Back"], sports: ["all"], description: "Sit on the floor with legs straight. Reach forward toward your toes keeping your back as flat as possible. Hold 40 seconds.", injury_prevention_for: ["Hamstring strain", "Lower back pain"] },
  { name: "Pigeon Pose", type: "stretch", difficulty: "medium", duration_seconds: 60, target_areas: ["Hips", "Glutes", "Piriformis"], sports: ["running","cycling","football","rugby","martial_arts"], description: "From a plank position, bring one knee forward and place it behind your wrist. Extend the other leg straight back. Lower your hips toward the floor and hold. 60 seconds each side.", injury_prevention_for: ["Hip pain", "Sciatica", "Lower back pain"] },
  { name: "IT Band Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["IT Band", "Knees", "Hips"], sports: ["running","cycling"], description: "Cross one leg behind the other and lean away from the back leg. You should feel a stretch along the outside of your hip and thigh. Hold 30 seconds each side.", injury_prevention_for: ["Knee pain", "IT band syndrome"] },
  { name: "Calf Stretch (Wall)", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Calves", "Ankles"], sports: ["running","basketball","football","tennis"], description: "Stand facing a wall, place one foot back with heel flat on the floor. Lean into the wall until you feel a stretch in your calf. Hold 30 seconds each side.", injury_prevention_for: ["Achilles tendon", "Calf strain", "Ankle pain"] },
  { name: "Soleus Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Calves", "Achilles"], sports: ["running","basketball","football"], description: "Same as calf stretch but bend your back knee slightly. This targets the deeper calf muscle. Hold 30 seconds each side.", injury_prevention_for: ["Achilles tendon", "Ankle pain"] },
  { name: "Chest Doorway Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Chest", "Shoulders", "Pecs"], sports: ["swimming","weightlifting","rugby","tennis","baseball"], description: "Stand in a doorway, place forearms on the door frame at 90 degrees. Step forward until you feel a stretch across your chest. Hold 30 seconds.", injury_prevention_for: ["Shoulder pain", "Rotator cuff"] },
  { name: "Sleeper Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Shoulders", "Rotator Cuff"], sports: ["swimming","tennis","baseball","weightlifting"], description: "Lie on your side with your arm at 90 degrees. Use your other hand to gently push your forearm down toward the floor. Hold 30 seconds each side.", injury_prevention_for: ["Shoulder pain", "Rotator cuff", "SLAP tear"] },
  { name: "Cross Body Shoulder Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Shoulders", "Upper Back"], sports: ["all"], description: "Pull one arm across your chest and hold it with the other arm. Keep your shoulder down. Hold 30 seconds each side.", injury_prevention_for: ["Shoulder pain", "Upper back pain"] },
  { name: "Neck Side Stretch", type: "stretch", difficulty: "easy", duration_seconds: 20, target_areas: ["Neck", "Traps"], sports: ["rugby","weightlifting","swimming"], description: "Tilt your head to one side, bringing your ear toward your shoulder. Gently add pressure with your hand. Hold 20 seconds each side.", injury_prevention_for: ["Neck pain", "Headaches"] },
  { name: "Thoracic Rotation Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Upper Back", "Spine"], sports: ["golf","tennis","swimming","weightlifting"], description: "Sit on the floor with knees bent. Rotate your upper body to one side, placing your hand behind you for support. Hold 30 seconds each side.", injury_prevention_for: ["Upper back pain", "Lower back pain"] },
  { name: "Adductor Groin Stretch", type: "stretch", difficulty: "easy", duration_seconds: 40, target_areas: ["Groin", "Adductors", "Hips"], sports: ["football","basketball","rugby","hockey"], description: "Sit on the floor with soles of feet together, knees out to the sides. Gently press knees toward the floor. Hold 40 seconds.", injury_prevention_for: ["Groin strain", "Hip pain"] },
  { name: "Piriformis Stretch", type: "stretch", difficulty: "easy", duration_seconds: 40, target_areas: ["Glutes", "Piriformis", "Hips"], sports: ["running","cycling","football"], description: "Lie on your back, cross one ankle over the opposite knee. Pull the uncrossed leg toward your chest. Hold 40 seconds each side.", injury_prevention_for: ["Sciatica", "Hip pain", "Lower back pain"] },
  { name: "Ankle Dorsiflexion Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Ankles", "Calves"], sports: ["weightlifting","crossfit","basketball","football"], description: "Kneel and place one foot flat on the floor. Drive your knee forward over your toes until you feel a stretch in the ankle. Hold 30 seconds each side.", injury_prevention_for: ["Ankle pain", "Achilles tendon"] },
  { name: "Wrist Flexor Stretch", type: "stretch", difficulty: "easy", duration_seconds: 20, target_areas: ["Wrists", "Forearms"], sports: ["tennis","golf","baseball","weightlifting","gymnastics"], description: "Extend one arm in front, palm up. Use your other hand to gently pull fingers back toward you. Hold 20 seconds each side.", injury_prevention_for: ["Wrist pain", "Tennis elbow"] },
  { name: "Lat Stretch", type: "stretch", difficulty: "easy", duration_seconds: 30, target_areas: ["Back", "Lats", "Shoulders"], sports: ["swimming","weightlifting","gymnastics"], description: "Hold onto a pole or door frame at shoulder height. Sit back and allow your upper body to stretch to the side. Hold 30 seconds each side.", injury_prevention_for: ["Back pain", "Shoulder pain"] },

  // ─── MOBILITY ────────────────────────────────────────────────
  { name: "World's Greatest Stretch", type: "mobility", difficulty: "medium", duration_seconds: 45, target_areas: ["Hips", "Thoracic Spine", "Hamstrings", "Groin"], sports: ["all"], description: "Step forward into a lunge. Place your same-side hand inside your front foot. Rotate your opposite arm up toward the ceiling following it with your eyes. 45 seconds each side.", injury_prevention_for: ["Hip pain", "Lower back pain", "Hamstring strain"] },
  { name: "Hip 90/90 Mobility", type: "mobility", difficulty: "medium", duration_seconds: 60, target_areas: ["Hips", "Glutes", "Piriformis"], sports: ["football","rugby","martial_arts","running"], description: "Sit with both legs bent at 90 degrees, one in front and one behind. Rotate slowly from hip to hip. 60 seconds total.", injury_prevention_for: ["Hip pain", "Sciatica"] },
  { name: "Thoracic Extension on Foam Roller", type: "mobility", difficulty: "easy", duration_seconds: 60, target_areas: ["Upper Back", "Thoracic Spine"], sports: ["all"], description: "Place foam roller horizontally under your upper back. Support your head with your hands. Gently extend backwards over the roller, moving up and down your thoracic spine. 60 seconds.", injury_prevention_for: ["Upper back pain", "Shoulder pain", "Neck pain"] },
  { name: "Cat-Cow Spinal Mobility", type: "mobility", difficulty: "easy", duration_seconds: 60, reps: 15, target_areas: ["Spine", "Lower Back", "Core"], sports: ["all"], description: "On hands and knees. Arch your back up toward the ceiling (cat), then drop it toward the floor (cow). Move slowly through each position. 15 reps.", injury_prevention_for: ["Lower back pain", "Spine health"] },
  { name: "Ankle Circles", type: "mobility", difficulty: "easy", duration_seconds: 30, target_areas: ["Ankles"], sports: ["all"], description: "Lift one foot off the floor. Rotate your ankle slowly in large circles — 10 clockwise, 10 anticlockwise. Each foot.", injury_prevention_for: ["Ankle sprain", "Ankle instability"] },
  { name: "Hip Circle Mobility", type: "mobility", difficulty: "easy", duration_seconds: 45, target_areas: ["Hips", "Lower Back"], sports: ["all"], description: "Stand with hands on hips. Make large slow circles with your hips — 10 each direction.", injury_prevention_for: ["Hip pain", "Lower back pain"] },
  { name: "Shoulder CARs", type: "mobility", difficulty: "medium", duration_seconds: 60, target_areas: ["Shoulders", "Rotator Cuff"], sports: ["swimming","tennis","baseball","weightlifting"], description: "Controlled articular rotation of the shoulder. Slowly rotate your arm in the largest circle possible, exploring the full range of motion. 5 reps each direction.", injury_prevention_for: ["Shoulder pain", "Rotator cuff"] },
  { name: "Thoracic Rotation (Quadruped)", type: "mobility", difficulty: "easy", duration_seconds: 45, reps: 10, target_areas: ["Upper Back", "Spine"], sports: ["golf","tennis","swimming"], description: "On hands and knees, place one hand behind your head. Rotate your elbow up toward the ceiling then down toward your opposite elbow. 10 reps each side.", injury_prevention_for: ["Upper back pain", "Lower back pain"] },
  { name: "Lateral Hip Mobility", type: "mobility", difficulty: "medium", duration_seconds: 45, target_areas: ["Hips", "Glutes", "Adductors"], sports: ["football","basketball","rugby","hockey"], description: "Stand with feet wide. Shift your weight side to side, bending one knee and keeping the other leg straight. Flow slowly between sides.", injury_prevention_for: ["Groin strain", "Hip pain"] },
  { name: "Knee to Wall Ankle Mobility", type: "mobility", difficulty: "easy", duration_seconds: 30, target_areas: ["Ankles", "Calves"], sports: ["weightlifting","crossfit","basketball"], description: "Place your toes 5cm from a wall. Drive your knee forward to touch the wall without lifting your heel. Progress by moving your foot further back.", injury_prevention_for: ["Ankle stiffness", "Achilles tendon"] },

  // ─── STRENGTH ────────────────────────────────────────────────
  { name: "Glute Bridge", type: "strength", difficulty: "easy", reps: 15, sets: 3, target_areas: ["Glutes", "Hamstrings", "Lower Back"], sports: ["all"], description: "Lie on your back with knees bent and feet flat on the floor. Drive through your heels to lift your hips toward the ceiling. Squeeze glutes at the top. Lower slowly. 3x15.", injury_prevention_for: ["Lower back pain", "Knee pain", "Hamstring strain"] },
  { name: "Single Leg Glute Bridge", type: "strength", difficulty: "medium", reps: 12, sets: 3, target_areas: ["Glutes", "Hamstrings", "Core"], sports: ["running","football","basketball"], description: "Same as glute bridge but extend one leg straight. Perform all reps on one side before switching. 3x12 each side.", injury_prevention_for: ["Knee pain", "Hip pain", "Lower back pain"] },
  { name: "Clamshell", type: "strength", difficulty: "easy", reps: 20, sets: 3, target_areas: ["Glutes", "Hip Abductors"], sports: ["running","cycling","football","basketball"], description: "Lie on your side with knees bent. Keeping feet together, lift your top knee up like a clamshell opening. Don't let your hips roll back. 3x20 each side.", injury_prevention_for: ["Knee pain", "Hip pain", "IT band syndrome"] },
  { name: "Nordic Hamstring Curl", type: "strength", difficulty: "hard", reps: 6, sets: 3, target_areas: ["Hamstrings"], sports: ["football","rugby","basketball","sprinting"], description: "Kneel with feet anchored. Slowly lower your body toward the floor by straightening your knees, resisting with your hamstrings. Use your hands to catch yourself. 3x6.", injury_prevention_for: ["Hamstring strain"] },
  { name: "Copenhagen Plank", type: "strength", difficulty: "hard", duration_seconds: 20, sets: 3, target_areas: ["Adductors", "Groin", "Core"], sports: ["football","rugby","hockey","basketball"], description: "Place your top foot on a bench in a side plank position. Lift your bottom leg to meet it. Hold 20 seconds each side.", injury_prevention_for: ["Groin strain", "Adductor strain"] },
  { name: "Wall Sit", type: "strength", difficulty: "medium", duration_seconds: 45, sets: 3, target_areas: ["Quads", "Glutes", "Knees"], sports: ["skiing","basketball","football","cycling"], description: "Slide your back down a wall until thighs are parallel to the floor. Hold for 45 seconds. Keep knees behind toes.", injury_prevention_for: ["Knee pain", "Quad weakness"] },
  { name: "Lateral Band Walk", type: "strength", difficulty: "easy", reps: 15, sets: 3, target_areas: ["Glutes", "Hip Abductors", "Knees"], sports: ["basketball","football","rugby","running"], description: "Place a resistance band around your ankles. Step sideways maintaining a slight squat position. Keep toes forward. 15 steps each direction.", injury_prevention_for: ["Knee pain", "IT band syndrome", "Hip pain"] },
  { name: "Single Leg Calf Raise", type: "strength", difficulty: "medium", reps: 20, sets: 3, target_areas: ["Calves", "Ankles", "Achilles"], sports: ["running","basketball","football","tennis"], description: "Stand on one foot. Rise up onto your toes slowly, then lower slowly. 3x20 each foot. Progress by adding weight.", injury_prevention_for: ["Achilles tendon", "Calf strain", "Ankle instability"] },
  { name: "Push-Up", type: "strength", difficulty: "medium", reps: 15, sets: 3, target_areas: ["Chest", "Shoulders", "Triceps", "Core"], sports: ["all"], description: "Start in a high plank. Lower your chest to the floor keeping elbows at 45 degrees. Push back up. Keep core tight throughout. 3x15.", injury_prevention_for: ["Shoulder pain", "Elbow pain"] },
  { name: "Band Pull-Apart", type: "strength", difficulty: "easy", reps: 20, sets: 3, target_areas: ["Upper Back", "Shoulders", "Rear Delts"], sports: ["swimming","tennis","baseball","weightlifting"], description: "Hold a resistance band in front with arms straight. Pull the band apart until it touches your chest. Squeeze shoulder blades together. 3x20.", injury_prevention_for: ["Shoulder pain", "Rotator cuff", "Posture"] },
  { name: "Face Pull", type: "strength", difficulty: "easy", reps: 15, sets: 3, target_areas: ["Shoulders", "Rotator Cuff", "Upper Back"], sports: ["swimming","tennis","baseball","weightlifting"], description: "Using a resistance band at face height, pull toward your face with elbows flared out. Externally rotate at the top. 3x15.", injury_prevention_for: ["Shoulder pain", "Rotator cuff"] },
  { name: "Single Leg Deadlift", type: "strength", difficulty: "medium", reps: 10, sets: 3, target_areas: ["Hamstrings", "Glutes", "Balance", "Core"], sports: ["running","football","basketball","rugby"], description: "Stand on one leg, hinge forward at the hip extending your other leg behind. Keep your back flat. Return to standing. 3x10 each side.", injury_prevention_for: ["Hamstring strain", "Ankle instability", "Knee pain"] },
  { name: "Reverse Nordic Curl", type: "strength", difficulty: "hard", reps: 8, sets: 3, target_areas: ["Quads", "Knees"], sports: ["football","basketball","rugby"], description: "Kneel with feet anchored. Slowly lean back keeping hips extended, then return to upright. This is a challenging quad exercise. 3x8.", injury_prevention_for: ["Knee pain", "Quad weakness"] },
  { name: "Hip Thrust", type: "strength", difficulty: "medium", reps: 12, sets: 3, target_areas: ["Glutes", "Hamstrings", "Core"], sports: ["sprinting","football","rugby","weightlifting"], description: "Sit with upper back against a bench, feet flat. Drive hips up until your body forms a straight line. Squeeze glutes at top. 3x12.", injury_prevention_for: ["Lower back pain", "Knee pain"] },
  { name: "Side Lying Hip Abduction", type: "strength", difficulty: "easy", reps: 20, sets: 3, target_areas: ["Glutes", "Hip Abductors"], sports: ["running","football","basketball"], description: "Lie on your side with legs straight. Lift your top leg toward the ceiling, keeping toes pointing forward. Lower slowly. 3x20 each side.", injury_prevention_for: ["Knee pain", "Hip pain", "IT band syndrome"] },

  // ─── ACTIVATION ──────────────────────────────────────────────
  { name: "Dead Bug", type: "activation", difficulty: "medium", reps: 10, sets: 3, target_areas: ["Core", "Lower Back"], sports: ["all"], description: "Lie on your back, arms pointing to ceiling, hips and knees at 90 degrees. Slowly lower one arm and opposite leg toward the floor without letting your lower back arch. Return and repeat. 3x10 each side.", injury_prevention_for: ["Lower back pain", "Core weakness"] },
  { name: "Bird Dog", type: "activation", difficulty: "easy", reps: 12, sets: 3, target_areas: ["Core", "Lower Back", "Glutes"], sports: ["all"], description: "On hands and knees. Extend one arm and opposite leg simultaneously. Hold 2 seconds at the top. Return and repeat. 3x12 each side.", injury_prevention_for: ["Lower back pain", "Core weakness"] },
  { name: "Pallof Press", type: "activation", difficulty: "medium", reps: 12, sets: 3, target_areas: ["Core", "Obliques"], sports: ["all"], description: "Stand side-on to a band or cable. Hold it at your chest. Press straight out, hold 2 seconds, return. The band will try to rotate you — resist it. 3x12 each side.", injury_prevention_for: ["Lower back pain", "Core weakness"] },
  { name: "Shoulder External Rotation", type: "activation", difficulty: "easy", reps: 15, sets: 3, target_areas: ["Rotator Cuff", "Shoulders"], sports: ["swimming","tennis","baseball","rugby"], description: "With a band around your wrists and elbows at 90 degrees at your sides, rotate your forearms outward. Keep elbows tucked. 3x15.", injury_prevention_for: ["Shoulder pain", "Rotator cuff"] },
  { name: "Scapular Push-Up", type: "activation", difficulty: "easy", reps: 15, sets: 3, target_areas: ["Shoulders", "Serratus Anterior", "Upper Back"], sports: ["swimming","tennis","baseball","weightlifting","gymnastics"], description: "In a high plank position. Without bending your elbows, let your shoulder blades come together, then push them apart. 3x15.", injury_prevention_for: ["Shoulder pain", "Winging scapula"] },
  { name: "Glute Activation with Band", type: "activation", difficulty: "easy", reps: 20, sets: 3, target_areas: ["Glutes", "Hips"], sports: ["all"], description: "Place a band around your knees. Lie on your back with knees bent. Push knees outward against the band then return. 3x20.", injury_prevention_for: ["Knee pain", "Hip pain"] },
  { name: "Ankle Alphabet", type: "activation", difficulty: "easy", duration_seconds: 30, target_areas: ["Ankles"], sports: ["basketball","football","rugby","running"], description: "Lift one foot off the floor. Write the alphabet in the air with your big toe, moving only at the ankle. Repeat with other foot.", injury_prevention_for: ["Ankle sprain", "Ankle instability"] },
  { name: "Terminal Knee Extension", type: "activation", difficulty: "easy", reps: 20, sets: 3, target_areas: ["Quads", "VMO", "Knees"], sports: ["all"], description: "Place a band behind your knee. Stand with a slight bend. Straighten your knee against the band resistance. 3x20 each leg.", injury_prevention_for: ["Knee pain", "ACL rehab"] },
  { name: "Prone Y-T-W", type: "activation", difficulty: "medium", reps: 10, sets: 3, target_areas: ["Upper Back", "Shoulders", "Rear Delts"], sports: ["swimming","tennis","baseball","rugby"], description: "Lie face down. Lift arms into Y, T, and W shapes, squeezing shoulder blades together. 10 reps in each position.", injury_prevention_for: ["Shoulder pain", "Rotator cuff", "Posture"] },

  // ─── BALANCE ─────────────────────────────────────────────────
  { name: "Single Leg Balance", type: "balance", difficulty: "easy", duration_seconds: 30, sets: 3, target_areas: ["Ankles", "Core", "Proprioception"], sports: ["all"], description: "Stand on one foot. Keep a slight bend in your knee. Hold for 30 seconds without touching your other foot down. Progress by closing your eyes. 3x30s each foot.", injury_prevention_for: ["Ankle sprain", "Knee pain"] },
  { name: "Single Leg Balance with Reach", type: "balance", difficulty: "medium", reps: 10, sets: 3, target_areas: ["Ankles", "Hips", "Core"], sports: ["all"], description: "Stand on one foot. Reach the other foot out to the front, side, and behind like a clock. 10 taps each direction. Repeat on other foot.", injury_prevention_for: ["Ankle sprain", "Knee pain", "Hip pain"] },
  { name: "Bosu Single Leg Balance", type: "balance", difficulty: "hard", duration_seconds: 30, sets: 3, target_areas: ["Ankles", "Core", "Proprioception"], sports: ["all"], description: "Stand on one foot on an unstable surface (BOSU, pillow, or folded mat). Hold 30 seconds. Progress by adding small movements or closing eyes.", injury_prevention_for: ["Ankle sprain", "Knee pain"] },
  { name: "Tandem Stance Balance", type: "balance", difficulty: "easy", duration_seconds: 30, sets: 3, target_areas: ["Ankles", "Core"], sports: ["all"], description: "Stand with one foot directly in front of the other (heel to toe). Hold for 30 seconds. Switch feet. Progress by closing your eyes.", injury_prevention_for: ["Ankle instability", "Balance issues"] },

  // ─── FOAM ROLL ───────────────────────────────────────────────
  { name: "IT Band Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 60, target_areas: ["IT Band", "Knees", "Hips"], sports: ["running","cycling"], description: "Lie on your side with the foam roller under your outer thigh. Roll slowly from hip to just above knee, pausing on tight spots. 60 seconds each side.", injury_prevention_for: ["IT band syndrome", "Knee pain"] },
  { name: "Thoracic Spine Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 60, target_areas: ["Upper Back", "Thoracic Spine"], sports: ["all"], description: "Sit with foam roller behind your upper back. Support your head with hands. Roll up and down the thoracic spine, extending over the roller at each level. 60 seconds.", injury_prevention_for: ["Upper back pain", "Shoulder pain", "Posture"] },
  { name: "Calf Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 45, target_areas: ["Calves", "Achilles"], sports: ["running","basketball","football"], description: "Sit with foam roller under your calves. Use your hands to lift your body and roll from ankle to knee. Cross one leg over for more pressure. 45 seconds each leg.", injury_prevention_for: ["Calf strain", "Achilles tendon"] },
  { name: "Quad Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 45, target_areas: ["Quads", "Knees"], sports: ["running","cycling","football","rugby"], description: "Lie face down with foam roller under your thighs. Roll from hip to just above knee. Rotate legs slightly inward and outward to hit different areas. 45 seconds each leg.", injury_prevention_for: ["Quad strain", "Knee pain"] },
  { name: "Glute Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 45, target_areas: ["Glutes", "Piriformis"], sports: ["all"], description: "Sit on the foam roller and cross one ankle over the opposite knee. Lean into the glute of the crossed leg and roll around to find tight spots. 45 seconds each side.", injury_prevention_for: ["Glute pain", "Sciatica", "Hip pain"] },
  { name: "Upper Back Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 60, target_areas: ["Upper Back", "Lats"], sports: ["swimming","weightlifting","rugby"], description: "Place foam roller under one side of your upper back. Arm extended overhead. Roll from armpit to mid-back. 60 seconds each side.", injury_prevention_for: ["Upper back pain", "Shoulder pain"] },
  { name: "Hamstring Foam Roll", type: "foam_roll", difficulty: "easy", duration_seconds: 45, target_areas: ["Hamstrings"], sports: ["running","football","rugby","basketball"], description: "Sit with foam roller under your thighs. Use your hands to lift your body and roll from glutes to just above knees. Cross one leg for more pressure. 45 seconds each leg.", injury_prevention_for: ["Hamstring strain", "Lower back pain"] },
  { name: "Hip Flexor Foam Roll", type: "foam_roll", difficulty: "medium", duration_seconds: 45, target_areas: ["Hip Flexors", "Quads"], sports: ["running","cycling","football"], description: "Lie face down with foam roller under one hip, slightly to the inside of the front. Roll slowly up and down the hip flexor area. 45 seconds each side.", injury_prevention_for: ["Hip pain", "Lower back pain"] },
];

export const LIBRARY_COUNT = EXERCISE_LIBRARY.length;
